### **Assignment: Introduction to Linear Algebra and NumPy**

#### **Objective:**
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.


### **Working with NumPy**

NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

**Task 1:** 
- Import the `numpy` library and check its version.


In [87]:
import numpy as np
print(np.__version__)

2.2.2



### **Creating a NumPy Array:**

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

**Task 2:**
- Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
- Generate an array of 10 evenly spaced values between 0 and 5.

In [88]:
# Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5]
lst = [1, 2, 3, 4, 5]
arr1 = np.array(lst)
arr1

array([1, 2, 3, 4, 5])

In [89]:
# Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
arr2 = np.random.randint(low = 1, high = 9, size = (3,3))
arr2

array([[5, 3, 3],
       [5, 4, 8],
       [1, 6, 2]], dtype=int32)

In [90]:
# Generate an array of 10 evenly spaced values between 0 and 5.
np.linspace(start = 0, stop = 5, num=10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### **Indexing and Slicing Arrays:**

Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**
- Access the element in the second row, third column of the 2D array you created above.
- Slice the first two rows and the first two columns from the same array.
- Modify the value in the last row and first column to 100.


In [91]:
# Access the element in the second row, third column of the 2D array you created above.
arr2[1][2]

np.int32(8)

In [92]:
#Slice the first two rows and the first two columns from the same array.
slice = arr2[:2,:2]
print(slice)

[[5 3]
 [5 4]]


In [93]:
#Modify the value in the last row and first column to 100.
arr2[2,0]=100
print(arr2)

[[  5   3   3]
 [  5   4   8]
 [100   6   2]]


### **Properties and Methods of NumPy Arrays**

NumPy arrays have several useful properties and methods.

**Task 4:**
- Find the shape, size, and data type of the 2D array.
- Change the 1D array into a 2D array of shape (5,1).
- Flatten a multi-dimensional array back into a 1D array.

In [94]:
# Find the shape, size, and data type of the 2D array.
print(arr2)
print("\nshape:",arr2.shape)
print("size:",arr2.size)
print("datatype:",arr2.dtype)

[[  5   3   3]
 [  5   4   8]
 [100   6   2]]

shape: (3, 3)
size: 9
datatype: int32


In [95]:
#Change the 1D array into a 2D array of shape (5,1).
arr1=np.random.randint(1,10,size = 5)
print("1D array:\n",arr1)

reshaped= arr1.reshape(5,1)
print("2D array:\n",reshaped)
print("shape:",reshaped.shape)

1D array:
 [5 2 7 3 8]
2D array:
 [[5]
 [2]
 [7]
 [3]
 [8]]
shape: (5, 1)


In [96]:
#Flatten a multi-dimensional array back into a 1D array.
arr3 = np.random.randint(low = 0, high = 50,size = (8,3,3))
print("Multi dimensional array:\n",arr3)

Multi dimensional array:
 [[[41 20 44]
  [25 17 15]
  [43  7 14]]

 [[14 44 18]
  [49 39 20]
  [44 24 22]]

 [[44  4 26]
  [ 7  1 46]
  [21  6 24]]

 [[21 37 40]
  [44 28 47]
  [48 26 33]]

 [[46 27  2]
  [ 7  3 49]
  [20  3 28]]

 [[15 41  4]
  [17 28 34]
  [49 40 31]]

 [[35 32 22]
  [25 34 48]
  [23 44 11]]

 [[35  0  7]
  [10  8 15]
  [35 25 43]]]


In [97]:
flatten_array = arr3.flatten()
print("flattened array:\n",flatten_array)

flattened array:
 [41 20 44 25 17 15 43  7 14 14 44 18 49 39 20 44 24 22 44  4 26  7  1 46
 21  6 24 21 37 40 44 28 47 48 26 33 46 27  2  7  3 49 20  3 28 15 41  4
 17 28 34 49 40 31 35 32 22 25 34 48 23 44 11 35  0  7 10  8 15 35 25 43]


### **Operations on NumPy Arrays**

Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**
- Add 5 to every element in the 1D array.
- Multiply the 2D array by 3.
- Perform matrix multiplication between the following two arrays:  
    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

In [112]:
# Add 5 to every element in the 1D array.
print("Array of 1 dimension is:\n",arr1)
print("Upon adding 5, we get:\n",(arr1+5))

Array of 1 dimension is:
 [5 2 7 3 8]
Upon adding 5, we get:
 [10  7 12  8 13]


In [113]:
# Multiply the 2D array by 3.
print("Array of 2 dimension is:\n",arr2)
print("Upon muntiplying by 3 we get:\n",arr2*3)

Array of 2 dimension is:
 [[  5   3   3]
 [  5   4   8]
 [100   6   2]]
Upon muntiplying by 3 we get:
 [[ 15   9   9]
 [ 15  12  24]
 [300  18   6]]


In [114]:
#Perform matrix multiplication between the following two arrays:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
arr_mun = np.dot(A,B)
print("Product:\n",arr_mun)

Product:
 [[19 22]
 [43 50]]


### **Understanding Broadcasting**

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

**Task 6:**
- Create a 3x3 matrix of ones and a 1D array of length 3.
- Add the 1D array to each row of the matrix using broadcasting.

In [115]:
# Create a 3x3 matrix of ones and a 1D array of length 3.
arr_ones = np.ones(shape = (3,3))
print("Ones Array:\n",arr_ones)
#Add the 1D array to each row of the matrix using broadcasting.
arr5= np.array([1,2,3])
print("1D Array:\n",arr5)
arr_sum =arr5+arr_ones
print("Sum:\n",arr_sum)


Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1D Array:
 [1 2 3]
Sum:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
