### **Assignment: Introduction to Linear Algebra and NumPy**

#### **Objective:**
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.


### **Working with NumPy**

NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

**Task 1:** 
- Import the `numpy` library and check its version.


In [2]:
import numpy as np
print(np.__version__)

2.2.1



### **Creating a NumPy Array:**

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

**Task 2:**
- Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
- Generate an array of 10 evenly spaced values between 0 and 5.

In [3]:
# Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5]
lst = [1, 2, 3, 4, 5]
arr1 = np.array(lst)
arr1

array([1, 2, 3, 4, 5])

In [4]:
# Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
arr2 = np.random.randint(low = 1, high = 9, size = (3,3))
arr2

array([[7, 8, 7],
       [8, 5, 5],
       [6, 6, 4]], dtype=int32)

In [5]:
# Generate an array of 10 evenly spaced values between 0 and 5.
np.linspace(start = 0, stop = 5, num=10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### **Indexing and Slicing Arrays:**

Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**
- Access the element in the second row, third column of the 2D array you created above.
- Slice the first two rows and the first two columns from the same array.
- Modify the value in the last row and first column to 100.


In [6]:
# Access the element in the second row, third column of the 2D array you created above.
arr2[1][2]

np.int32(5)

In [7]:
#Slice the first two rows and the first two columns from the same array.
slice = arr2[:2,:2]
print(slice)

[[7 8]
 [8 5]]


In [8]:
#Modify the value in the last row and first column to 100.
arr2[2,0]=100
print(arr2)

[[  7   8   7]
 [  8   5   5]
 [100   6   4]]


### **Properties and Methods of NumPy Arrays**

NumPy arrays have several useful properties and methods.

**Task 4:**
- Find the shape, size, and data type of the 2D array.
- Change the 1D array into a 2D array of shape (5,1).
- Flatten a multi-dimensional array back into a 1D array.

In [9]:
# Find the shape, size, and data type of the 2D array.
print(arr2)
print("\nshape:",arr2.shape)
print("size:",arr2.size)
print("datatype:",arr2.dtype)

[[  7   8   7]
 [  8   5   5]
 [100   6   4]]

shape: (3, 3)
size: 9
datatype: int32


In [10]:
#Change the 1D array into a 2D array of shape (5,1).
arr1=np.random.randint(1,10,size = 5)
print("1D array:\n",arr1)

reshaped= arr1.reshape(5,1)
print("2D array:\n",reshaped)
print("shape:",reshaped.shape)

1D array:
 [2 9 9 5 1]
2D array:
 [[2]
 [9]
 [9]
 [5]
 [1]]
shape: (5, 1)


In [11]:
#Flatten a multi-dimensional array back into a 1D array.
arr3 = np.random.randint(low = 0, high = 50,size = (8,3,3))
print("Multi dimensional array:\n",arr3)

Multi dimensional array:
 [[[39 34 16]
  [45 40 27]
  [ 0 46 21]]

 [[23 42 40]
  [ 3 14 35]
  [ 9 44  1]]

 [[46 42 13]
  [43 34 44]
  [41 47 32]]

 [[36 15 37]
  [44 15 32]
  [40 23  6]]

 [[15 19  5]
  [18 39 44]
  [11  3 49]]

 [[16 32 24]
  [15 22 23]
  [27 13 33]]

 [[38 14 13]
  [23  2 34]
  [43 21  6]]

 [[ 8 26 48]
  [21  8 26]
  [41 33 22]]]


In [12]:
flatten_array = arr3.flatten()
print("flattened array:\n",flatten_array)

flattened array:
 [39 34 16 45 40 27  0 46 21 23 42 40  3 14 35  9 44  1 46 42 13 43 34 44
 41 47 32 36 15 37 44 15 32 40 23  6 15 19  5 18 39 44 11  3 49 16 32 24
 15 22 23 27 13 33 38 14 13 23  2 34 43 21  6  8 26 48 21  8 26 41 33 22]


### **Operations on NumPy Arrays**

Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**
- Add 5 to every element in the 1D array.
- Multiply the 2D array by 3.
- Perform matrix multiplication between the following two arrays:  
    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

In [13]:
# Add 5 to every element in the 1D array.
print("Array of 1 dimension is:\n",arr1)
print("Upon adding 5, we get:\n",(arr1+5))

Array of 1 dimension is:
 [2 9 9 5 1]
Upon adding 5, we get:
 [ 7 14 14 10  6]


In [14]:
# Multiply the 2D array by 3.
print("Array of 2 dimension is:\n",arr2)
print("Upon muntiplying by 3 we get:\n",arr2*3)

Array of 2 dimension is:
 [[  7   8   7]
 [  8   5   5]
 [100   6   4]]
Upon muntiplying by 3 we get:
 [[ 21  24  21]
 [ 24  15  15]
 [300  18  12]]


In [15]:
#Perform matrix multiplication between the following two arrays:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
arr_mun = np.dot(A,B)
print("Product:\n",arr_mun)

Product:
 [[19 22]
 [43 50]]


### **Understanding Broadcasting**

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

**Task 6:**
- Create a 3x3 matrix of ones and a 1D array of length 3.
- Add the 1D array to each row of the matrix using broadcasting.

In [17]:
# Create a 3x3 matrix of ones and a 1D array of length 3.
arr_ones = np.ones(shape = (3,3))
print("Ones Array:\n",arr_ones)
#Add the 1D array to each row of the matrix using broadcasting.
arr5= np.array([5,8,0])
print("1D Array:\n",arr5)
arr_sum =arr5+arr_ones
print("Sum:\n",arr_sum)


Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1D Array:
 [5 8 0]
Sum:
 [[6. 9. 1.]
 [6. 9. 1.]
 [6. 9. 1.]]
