## Type Conversion In Array

<arrayname>.astype(np.<type>)  
Example:
a = np.array([1,225,3], dtype = np.int16)  #dtype = np.int16 provides data type with max byte 16.

In [21]:
import numpy as np

a = np.array([1,10,3], dtype = np.int16)  #dtype = np.int16 provides data type with max byte 16.

In [22]:
a

array([  1, 225,   3], dtype=int16)

In [23]:
a.dtype

dtype('int16')

In [24]:
b = a.astype(np.float16)

In [25]:
b

array([  1., 225.,   3.], dtype=float16)

In [26]:
b.dtype #data type changed to float 16.

dtype('float16')

In [27]:
c  = np.array([1,0,-3,1], dtype=np.bool) #converts any number to true and 0 to false

In [28]:
c

array([ True, False,  True,  True])