**Array Methods**
-

shape  
ndim  
dtype  
sum  
product  
max  
flatten  
ravel  
vstack  
hstack  

In [21]:
import numpy as np

In [22]:
arr = np.random.randint(10,20, size = (3,4,5))

In [23]:
arr

array([[[14, 13, 15, 18, 19],
        [16, 13, 19, 18, 14],
        [14, 10, 14, 17, 13],
        [12, 19, 17, 16, 13]],

       [[17, 15, 16, 17, 11],
        [18, 19, 19, 18, 12],
        [12, 14, 17, 17, 12],
        [18, 19, 13, 12, 17]],

       [[19, 11, 13, 13, 17],
        [15, 16, 15, 18, 10],
        [17, 16, 13, 16, 17],
        [18, 18, 14, 19, 19]]], dtype=int32)

In [24]:
arr.shape

(3, 4, 5)

In [25]:
arr.ndim

3

In [26]:
arr.dtype #gives data type

dtype('int32')

In [27]:
arr.T  #Gives the transpose of the matrix

array([[[14, 17, 19],
        [16, 18, 15],
        [14, 12, 17],
        [12, 18, 18]],

       [[13, 15, 11],
        [13, 19, 16],
        [10, 14, 16],
        [19, 19, 18]],

       [[15, 16, 13],
        [19, 19, 15],
        [14, 17, 13],
        [17, 13, 14]],

       [[18, 17, 13],
        [18, 18, 18],
        [17, 17, 16],
        [16, 12, 19]],

       [[19, 11, 17],
        [14, 12, 10],
        [13, 12, 17],
        [13, 17, 19]]], dtype=int32)

In [30]:
arrt = arr.T

In [32]:
print(arrt)

[[[14 17 19]
  [16 18 15]
  [14 12 17]
  [12 18 18]]

 [[13 15 11]
  [13 19 16]
  [10 14 16]
  [19 19 18]]

 [[15 16 13]
  [19 19 15]
  [14 17 13]
  [17 13 14]]

 [[18 17 13]
  [18 18 18]
  [17 17 16]
  [16 12 19]]

 [[19 11 17]
  [14 12 10]
  [13 12 17]
  [13 17 19]]]


In [38]:
#reshape
arrt.shape

(5, 4, 3)

In [39]:
arrt.reshape(6,10) #must conserve all element..i.e. product of dimension should be same.

array([[14, 17, 19, 16, 18, 15, 14, 12, 17, 12],
       [18, 18, 13, 15, 11, 13, 19, 16, 10, 14],
       [16, 19, 19, 18, 15, 16, 13, 19, 19, 15],
       [14, 17, 13, 17, 13, 14, 18, 17, 13, 18],
       [18, 18, 17, 17, 16, 16, 12, 19, 19, 11],
       [17, 14, 12, 10, 13, 12, 17, 13, 17, 19]], dtype=int32)

In [40]:
arrt.reshape(4,15)

array([[14, 17, 19, 16, 18, 15, 14, 12, 17, 12, 18, 18, 13, 15, 11],
       [13, 19, 16, 10, 14, 16, 19, 19, 18, 15, 16, 13, 19, 19, 15],
       [14, 17, 13, 17, 13, 14, 18, 17, 13, 18, 18, 18, 17, 17, 16],
       [16, 12, 19, 19, 11, 17, 14, 12, 10, 13, 12, 17, 13, 17, 19]],
      dtype=int32)

In [45]:
arrt.reshape(2,2,-1)

array([[[14, 17, 19, 16, 18, 15, 14, 12, 17, 12, 18, 18, 13, 15, 11],
        [13, 19, 16, 10, 14, 16, 19, 19, 18, 15, 16, 13, 19, 19, 15]],

       [[14, 17, 13, 17, 13, 14, 18, 17, 13, 18, 18, 18, 17, 17, 16],
        [16, 12, 19, 19, 11, 17, 14, 12, 10, 13, 12, 17, 13, 17, 19]]],
      dtype=int32)