In [35]:
import numpy as np

In [36]:
list1 = [2,3,4]

In [37]:
arr1 = np.array(list1)

In [38]:
arr1

array([2, 3, 4])

In [39]:
type(arr1)

numpy.ndarray

In [40]:
arr1.shape

(3,)

In [41]:
arr1.ndim

1

In [46]:
list2 = [[2,3,4],
         [2,3,4],
         [2,3,4]]

In [47]:
arr2 = np.array(list2)

In [48]:
arr2.shape

(3, 3)

In [49]:
arr2.ndim

2

In [52]:
np.zeros(shape = (6,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [67]:
np.ones(shape = (3,5,2)) # 3 such matrixes of dimension 5*2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [61]:
np.identity(5) #identity matrix of dimension 5*5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
np.full(shape=(4,2,2),fill_value = 3.5)

array([[[3.5, 3.5],
        [3.5, 3.5]],

       [[3.5, 3.5],
        [3.5, 3.5]],

       [[3.5, 3.5],
        [3.5, 3.5]],

       [[3.5, 3.5],
        [3.5, 3.5]]])

In [72]:
np.random.rand(3,4,5) #creates array with random member from [0,1) --->3 matrixes of size 4*5

array([[[0.31556228, 0.65150765, 0.03621092, 0.50248466, 0.03142547],
        [0.70298817, 0.05964064, 0.8912674 , 0.41145193, 0.88062566],
        [0.57716782, 0.26503424, 0.85630717, 0.17444391, 0.74014367],
        [0.0093359 , 0.49519704, 0.30186337, 0.47786193, 0.69758806]],

       [[0.52356276, 0.20985813, 0.35580011, 0.56478756, 0.12193562],
        [0.08748006, 0.75662621, 0.92846588, 0.53564398, 0.885803  ],
        [0.5387699 , 0.87879905, 0.19330978, 0.4424615 , 0.3413806 ],
        [0.99112299, 0.15452996, 0.60054958, 0.81126938, 0.5263187 ]],

       [[0.39699052, 0.40385339, 0.92714548, 0.70206097, 0.04268087],
        [0.76191404, 0.31292081, 0.26478388, 0.78066383, 0.62292282],
        [0.64475247, 0.97429699, 0.99690268, 0.67195606, 0.22890346],
        [0.8799662 , 0.28634363, 0.82794014, 0.42809643, 0.0710926 ]]])

In [76]:
np.linspace(start = 0, stop = 10, num = 11) #works like arithmetic series

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [80]:
np.linspace(start = (0,1,4) , stop = (10,20,30), num = 5 , axis = 0) #axis 0 creates row-wise -> working in arithmetic sequence rowwise

array([[ 0.  ,  1.  ,  4.  ],
       [ 2.5 ,  5.75, 10.5 ],
       [ 5.  , 10.5 , 17.  ],
       [ 7.5 , 15.25, 23.5 ],
       [10.  , 20.  , 30.  ]])

In [81]:
np.linspace(start = (0,1,4) , stop = (10,20,30), num = 5 , axis = 1) #axis 1 creates column-wise-->works in arithmetic sequence columnwise

array([[ 0.  ,  2.5 ,  5.  ,  7.5 , 10.  ],
       [ 1.  ,  5.75, 10.5 , 15.25, 20.  ],
       [ 4.  , 10.5 , 17.  , 23.5 , 30.  ]])

**Accessing an Array** 
-

In [168]:
import numpy as np

In [169]:
a = np.array([2,3,4,5])

In [170]:
a[2] #provides third element

np.int64(4)

In [171]:
#2D
b = np.random.randint(0,10,(2,3))

In [172]:
b

array([[7, 9, 9],
       [5, 8, 9]], dtype=int32)

In [173]:
b[0]

array([7, 9, 9], dtype=int32)

In [174]:
b[1]

array([5, 8, 9], dtype=int32)

In [175]:
print(b[0][2])

9


In [176]:
#3D
c = np.random.randint(0,10,(4,2,3))

In [177]:
print(c)

[[[6 4 5]
  [3 9 5]]

 [[4 5 8]
  [1 8 1]]

 [[4 1 9]
  [0 0 7]]

 [[1 9 6]
  [3 7 5]]]


In [178]:
c[1][1][1] #gives element in position 1*1 from matrix in position 1.  *NOTE*->Index starts from 0.

np.int32(8)

In [179]:
#to access the last element 9 of third matrix:
c[3][1][2]    #3 means matrix in position 3 starting index from 0....[1][2] means element in position 1*2 in the matrix

np.int32(5)

In [180]:
#3D
d = np.random.randint(0,10,(5,5))

In [181]:
d

array([[5, 1, 8, 6, 4],
       [9, 7, 9, 7, 7],
       [4, 3, 5, 8, 3],
       [1, 7, 8, 2, 3],
       [3, 1, 0, 7, 0]], dtype=int32)

In [182]:
d[::2]  #sliced row such that starts from start and step = 2

array([[5, 1, 8, 6, 4],
       [4, 3, 5, 8, 3],
       [3, 1, 0, 7, 0]], dtype=int32)

In [183]:
d[::2,::2]  #sliced row and column such that in both start = start end = end step = 2

array([[5, 8, 4],
       [4, 5, 3],
       [3, 0, 0]], dtype=int32)

In [184]:
d[::2,::2]

array([[5, 8, 4],
       [4, 5, 3],
       [3, 0, 0]], dtype=int32)

In [185]:
#3D
e = np.random.randint(0,10,(3,5,5))

In [186]:
e.shape

(3, 5, 5)

In [187]:
e[::2,::2, ::2]

array([[[5, 2, 9],
        [9, 3, 5],
        [6, 4, 7]],

       [[2, 3, 5],
        [7, 1, 9],
        [2, 9, 4]]], dtype=int32)

**Boolean or Mask Indexing**
-

In [209]:
f = np.random.randint(1,7,(5,6))

In [210]:
f

array([[3, 2, 5, 5, 5, 1],
       [6, 4, 4, 5, 4, 2],
       [1, 4, 3, 3, 2, 3],
       [1, 6, 1, 4, 5, 4],
       [6, 3, 2, 4, 5, 2]], dtype=int32)

In [211]:
mask = f>=5
mask

array([[False, False,  True,  True,  True, False],
       [ True, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False,  True, False],
       [ True, False, False, False,  True, False]])

In [212]:
f[mask]

array([5, 5, 5, 6, 5, 6, 5, 6, 5], dtype=int32)

In [217]:
f

array([[3, 2, 5, 5, 5, 1],
       [6, 4, 4, 5, 4, 2],
       [1, 4, 3, 3, 2, 3],
       [1, 6, 1, 4, 5, 4],
       [6, 3, 2, 4, 5, 2]], dtype=int32)

In [222]:
mask = [True, False, False , True, True] #T= first row f f f = 2,3 rows tt = 4,5 rows-->result gives 1,4,5 rows

In [224]:
f[mask] #gives the rows which are true and ignores rows which are false

array([[3, 2, 5, 5, 5, 1],
       [1, 6, 1, 4, 5, 4],
       [6, 3, 2, 4, 5, 2]], dtype=int32)