**Array Operation**
-
  pow()  
  sqrt()  

In [1]:
import numpy as np

In [5]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[1,2,3],[9,8,7]])

## Arithmetic Operation

In [7]:
a + b #sum of matrices

array([[ 5,  7,  9],
       [14, 15, 16]])

In [8]:
np.add(a,b) #sum of matrices

array([[ 5,  7,  9],
       [14, 15, 16]])

In [12]:
a-b #difference of matrices

array([[ 3,  3,  3],
       [-4, -1,  2]])

In [13]:
np.subtract(a,b) #difference of matrices

array([[ 3,  3,  3],
       [-4, -1,  2]])

In [15]:
a * b

array([[ 4, 10, 18],
       [45, 56, 63]])

In [17]:
np.multiply(a,b)

array([[ 4, 10, 18],
       [45, 56, 63]])

In [18]:
np.square(b) #square of matrix b

array([[ 1,  4,  9],
       [81, 64, 49]])

In [21]:
np.pow(a,5) #5th power of matrix a

array([[      4,      25,     216],
       [1953125, 5764801, 4782969]])

In [22]:
np.pow(a,b) #bth power of matrix a-->matches the position of matrix and raise the power to respective element in b

array([[      4,      25,     216],
       [1953125, 5764801, 4782969]])

In [24]:
a%b #divides a by b

array([[0, 1, 0],
       [5, 7, 2]])

In [28]:
np.divmod(a,b) #gives matrix of quotient first and the remainder

(array([[4, 2, 2],
        [0, 0, 1]]),
 array([[0, 1, 0],
        [5, 7, 2]]))

In [29]:
a

array([[4, 5, 6],
       [5, 7, 9]])

In [30]:
b

array([[1, 2, 3],
       [9, 8, 7]])

In [27]:
np.power(a,b)

array([[      4,      25,     216],
       [1953125, 5764801, 4782969]])

In [33]:
#can stack multiple functions too-->provides absolute value of result of subtraction
np.abs(
    np.subtract(a,b)
)

array([[3, 3, 3],
       [4, 1, 2]])