In [2]:
import numpy as np

In [3]:
a = np.random.randint(0,10,size = (3,5,5))

In [4]:
a

array([[[1, 2, 9, 6, 1],
        [9, 3, 9, 5, 7],
        [0, 4, 2, 4, 4],
        [7, 3, 2, 6, 0],
        [1, 1, 0, 9, 4]],

       [[7, 1, 2, 2, 5],
        [7, 2, 5, 9, 0],
        [7, 0, 0, 9, 5],
        [9, 2, 5, 7, 9],
        [9, 1, 7, 8, 9]],

       [[3, 8, 3, 0, 7],
        [9, 0, 7, 5, 1],
        [7, 7, 0, 3, 3],
        [3, 5, 8, 9, 0],
        [5, 1, 9, 6, 7]]], dtype=int32)

In [5]:
a.flatten()  #converts into a single dimension array(rowwise)

array([1, 2, 9, 6, 1, 9, 3, 9, 5, 7, 0, 4, 2, 4, 4, 7, 3, 2, 6, 0, 1, 1,
       0, 9, 4, 7, 1, 2, 2, 5, 7, 2, 5, 9, 0, 7, 0, 0, 9, 5, 9, 2, 5, 7,
       9, 9, 1, 7, 8, 9, 3, 8, 3, 0, 7, 9, 0, 7, 5, 1, 7, 7, 0, 3, 3, 3,
       5, 8, 9, 0, 5, 1, 9, 6, 7], dtype=int32)

In [6]:
a.flatten("F") #converts int single dimension array column wise in order of first element of each matrix

array([1, 7, 3, 9, 7, 9, 0, 7, 7, 7, 9, 3, 1, 9, 5, 2, 1, 8, 3, 2, 0, 4,
       0, 7, 3, 2, 5, 1, 1, 1, 9, 2, 3, 9, 5, 7, 2, 0, 0, 2, 5, 8, 0, 7,
       9, 6, 2, 0, 5, 9, 5, 4, 9, 3, 6, 7, 9, 9, 8, 6, 1, 5, 7, 7, 0, 1,
       4, 5, 3, 0, 9, 0, 4, 9, 7], dtype=int32)

In [7]:
a.sum()

np.int64(342)

In [8]:
a

array([[[1, 2, 9, 6, 1],
        [9, 3, 9, 5, 7],
        [0, 4, 2, 4, 4],
        [7, 3, 2, 6, 0],
        [1, 1, 0, 9, 4]],

       [[7, 1, 2, 2, 5],
        [7, 2, 5, 9, 0],
        [7, 0, 0, 9, 5],
        [9, 2, 5, 7, 9],
        [9, 1, 7, 8, 9]],

       [[3, 8, 3, 0, 7],
        [9, 0, 7, 5, 1],
        [7, 7, 0, 3, 3],
        [3, 5, 8, 9, 0],
        [5, 1, 9, 6, 7]]], dtype=int32)

In [9]:
a.sum(axis = 0)

array([[11, 11, 14,  8, 13],
       [25,  5, 21, 19,  8],
       [14, 11,  2, 16, 12],
       [19, 10, 15, 22,  9],
       [15,  3, 16, 23, 20]])

In [10]:
a.sum(axis = 1)

array([[18, 13, 22, 30, 16],
       [39,  6, 19, 35, 28],
       [27, 21, 27, 23, 18]])

In [11]:
b = np.random.randint(0,7,size = (2,2,2))

In [12]:
b

array([[[5, 0],
        [5, 0]],

       [[5, 4],
        [3, 1]]], dtype=int32)

In [13]:
b.prod(dtype =float)

np.float64(0.0)

In [14]:
b.prod(axis = 0)

array([[25,  0],
       [15,  0]])

In [15]:
b.cumsum() #cumulative sum-->adds members from first with second and then sum with third and so on

array([ 5,  5, 10, 10, 15, 19, 22, 23])

In [16]:
b.max()

np.int32(5)

In [17]:
b.max(axis = 0) #max value in row

array([[5, 4],
       [5, 1]], dtype=int32)

In [18]:
b.max(axis = 1) #max value in column

array([[5, 0],
       [5, 4]], dtype=int32)

In [19]:
b.argmax()#gives index of maximum value

np.int64(0)

In [20]:
b.clip(2.5) #provides value between 2 and 5-->lower than 2 is changed to 2 and higher than 5 is changed to 5

array([[[5. , 2.5],
        [5. , 2.5]],

       [[5. , 4. ],
        [3. , 2.5]]])

In [21]:
arr1= np.random.randint(low = -10,high = 10, size = (2,3))
arr2= np.random.randint(low = -10,high = 10, size = (2,3))


In [22]:
arr1, arr2 #stacks arrow 

(array([[-10,   9,  -3],
        [ -6,   0,   5]], dtype=int32),
 array([[-3, -3, -1],
        [-1,  7,  1]], dtype=int32))

In [23]:
np.vstack((arr1,arr2)) #same column required in vertical stack-->mostly used stack

array([[-10,   9,  -3],
       [ -6,   0,   5],
       [ -3,  -3,  -1],
       [ -1,   7,   1]], dtype=int32)

In [24]:
np.hstack((arr1,arr2)) #same column required in horizontal stack

array([[-10,   9,  -3,  -3,  -3,  -1],
       [ -6,   0,   5,  -1,   7,   1]], dtype=int32)

In [25]:
np.concatenate((arr1,arr2),axis = 0) #stacks vertically

array([[-10,   9,  -3],
       [ -6,   0,   5],
       [ -3,  -3,  -1],
       [ -1,   7,   1]], dtype=int32)

In [26]:
np.concatenate((arr1,arr2),axis = 1) #stacks horizontally

array([[-10,   9,  -3,  -3,  -3,  -1],
       [ -6,   0,   5,  -1,   7,   1]], dtype=int32)

In [27]:
np.ceil(a) #provides ceiling value(rounds of to next integer) for float elements.-->2.3=3, 2.9 = 3, 2.01 = 3

array([[[1, 2, 9, 6, 1],
        [9, 3, 9, 5, 7],
        [0, 4, 2, 4, 4],
        [7, 3, 2, 6, 0],
        [1, 1, 0, 9, 4]],

       [[7, 1, 2, 2, 5],
        [7, 2, 5, 9, 0],
        [7, 0, 0, 9, 5],
        [9, 2, 5, 7, 9],
        [9, 1, 7, 8, 9]],

       [[3, 8, 3, 0, 7],
        [9, 0, 7, 5, 1],
        [7, 7, 0, 3, 3],
        [3, 5, 8, 9, 0],
        [5, 1, 9, 6, 7]]], dtype=int32)

In [28]:
np.sin(a) #provides sin value of each element of matrix

array([[[ 0.84147098,  0.90929743,  0.41211849, -0.2794155 ,
          0.84147098],
        [ 0.41211849,  0.14112001,  0.41211849, -0.95892427,
          0.6569866 ],
        [ 0.        , -0.7568025 ,  0.90929743, -0.7568025 ,
         -0.7568025 ],
        [ 0.6569866 ,  0.14112001,  0.90929743, -0.2794155 ,
          0.        ],
        [ 0.84147098,  0.84147098,  0.        ,  0.41211849,
         -0.7568025 ]],

       [[ 0.6569866 ,  0.84147098,  0.90929743,  0.90929743,
         -0.95892427],
        [ 0.6569866 ,  0.90929743, -0.95892427,  0.41211849,
          0.        ],
        [ 0.6569866 ,  0.        ,  0.        ,  0.41211849,
         -0.95892427],
        [ 0.41211849,  0.90929743, -0.95892427,  0.6569866 ,
          0.41211849],
        [ 0.41211849,  0.84147098,  0.6569866 ,  0.98935825,
          0.41211849]],

       [[ 0.14112001,  0.98935825,  0.14112001,  0.        ,
          0.6569866 ],
        [ 0.41211849,  0.        ,  0.6569866 , -0.95892427,
          0

In [29]:
np.round(a,decimals = 3) #rounds off each elements to 3 decimal places

array([[[1, 2, 9, 6, 1],
        [9, 3, 9, 5, 7],
        [0, 4, 2, 4, 4],
        [7, 3, 2, 6, 0],
        [1, 1, 0, 9, 4]],

       [[7, 1, 2, 2, 5],
        [7, 2, 5, 9, 0],
        [7, 0, 0, 9, 5],
        [9, 2, 5, 7, 9],
        [9, 1, 7, 8, 9]],

       [[3, 8, 3, 0, 7],
        [9, 0, 7, 5, 1],
        [7, 7, 0, 3, 3],
        [3, 5, 8, 9, 0],
        [5, 1, 9, 6, 7]]], dtype=int32)

In [30]:
np.fix(c)

NameError: name 'c' is not defined

## Matrix Operation

Includes:  
            >Dot Product  
            >Inverse  

In [31]:
d=np.dot(a,c) #must match no of column of first matrix with no of row of second matrix

NameError: name 'c' is not defined

In [32]:
print(d)

NameError: name 'd' is not defined

In [ ]:
np.transpose(d) #changes row to column and vice versa

In [33]:
np.trace(b) #sum of elements in main diagonal

array([8, 1])

In [34]:
#solving equations: x+2y = 1, 3x+5y = 2
arrx = np.array([[1,2],
             [3,5]])
arry = np.array([1,2])


In [35]:
#solves the linear equations and give value of x and y
np.linalg.solve(arrx,arry)

array([-1.,  1.])

In [41]:
#solving linear equations using matrices
#2x+2y+2z = -3, x-y+z = 2, 2x-y-z = -6
arr1 = np.array([
    [2,2,1],[1,-1,1],[2,-1,-1]
])
arr2 = np.array([-3,2,-6])

array([-2., -1.,  3.])

In [42]:
#solves the linear equations and provide the value of x, y and z
np.linalg.solve(arr1,arr2)

array([-2., -1.,  3.])

In [45]:
x = np.dot(
    np.linalg.inv(arr1),arr2
)

In [46]:
x

array([-2., -1.,  3.])