In [42]:
import numpy as np

In [43]:
a = np.random.randint(0,10,size = (3,5,5))

In [44]:
a

array([[[3, 6, 2, 2, 6],
        [7, 5, 3, 7, 6],
        [0, 5, 5, 0, 5],
        [0, 1, 8, 1, 8],
        [5, 3, 8, 8, 1]],

       [[9, 8, 5, 9, 2],
        [5, 9, 6, 9, 4],
        [4, 2, 7, 7, 9],
        [5, 0, 3, 1, 4],
        [6, 8, 0, 6, 9]],

       [[7, 1, 3, 8, 3],
        [8, 3, 5, 9, 1],
        [8, 4, 3, 9, 4],
        [0, 6, 3, 3, 7],
        [3, 1, 4, 7, 0]]], dtype=int32)

In [45]:
a.flatten()  #converts into a single dimension array(rowwise)

array([3, 6, 2, 2, 6, 7, 5, 3, 7, 6, 0, 5, 5, 0, 5, 0, 1, 8, 1, 8, 5, 3,
       8, 8, 1, 9, 8, 5, 9, 2, 5, 9, 6, 9, 4, 4, 2, 7, 7, 9, 5, 0, 3, 1,
       4, 6, 8, 0, 6, 9, 7, 1, 3, 8, 3, 8, 3, 5, 9, 1, 8, 4, 3, 9, 4, 0,
       6, 3, 3, 7, 3, 1, 4, 7, 0], dtype=int32)

In [46]:
a.flatten("F") #converts int single dimension array column wise in order of first element of each matrix

array([3, 9, 7, 7, 5, 8, 0, 4, 8, 0, 5, 0, 5, 6, 3, 6, 8, 1, 5, 9, 3, 5,
       2, 4, 1, 0, 6, 3, 8, 1, 2, 5, 3, 3, 6, 5, 5, 7, 3, 8, 3, 3, 8, 0,
       4, 2, 9, 8, 7, 9, 9, 0, 7, 9, 1, 1, 3, 8, 6, 7, 6, 2, 3, 6, 4, 1,
       5, 9, 4, 8, 4, 7, 1, 9, 0], dtype=int32)

In [47]:
a.sum()

np.int64(352)

In [48]:
a

array([[[3, 6, 2, 2, 6],
        [7, 5, 3, 7, 6],
        [0, 5, 5, 0, 5],
        [0, 1, 8, 1, 8],
        [5, 3, 8, 8, 1]],

       [[9, 8, 5, 9, 2],
        [5, 9, 6, 9, 4],
        [4, 2, 7, 7, 9],
        [5, 0, 3, 1, 4],
        [6, 8, 0, 6, 9]],

       [[7, 1, 3, 8, 3],
        [8, 3, 5, 9, 1],
        [8, 4, 3, 9, 4],
        [0, 6, 3, 3, 7],
        [3, 1, 4, 7, 0]]], dtype=int32)

In [49]:
a.sum(axis = 0)

array([[19, 15, 10, 19, 11],
       [20, 17, 14, 25, 11],
       [12, 11, 15, 16, 18],
       [ 5,  7, 14,  5, 19],
       [14, 12, 12, 21, 10]])

In [50]:
a.sum(axis = 1)

array([[15, 20, 26, 18, 26],
       [29, 27, 21, 32, 28],
       [26, 15, 18, 36, 15]])

In [51]:
b = np.random.randint(0,7,size = (2,2,2))

In [52]:
b

array([[[1, 3],
        [2, 4]],

       [[0, 0],
        [2, 1]]], dtype=int32)

In [53]:
b.prod(dtype =float)

np.float64(0.0)

In [54]:
b.prod(axis = 0)

array([[0, 0],
       [4, 4]])

In [55]:
b.cumsum() #cumulative sum-->adds members from first with second and then sum with third and so on

array([ 1,  4,  6, 10, 10, 10, 12, 13])

In [56]:
b.max()

np.int32(4)

In [57]:
b.max(axis = 0) #max value in row

array([[1, 3],
       [2, 4]], dtype=int32)

In [58]:
b.max(axis = 1) #max value in column

array([[2, 4],
       [2, 1]], dtype=int32)

In [59]:
b.argmax()#gives index of maximum value

np.int64(3)

In [60]:
b.clip(2.5) #provides value between 2 and 5-->lower than 2 is changed to 2 and higher than 5 is changed to 5

array([[[2.5, 3. ],
        [2.5, 4. ]],

       [[2.5, 2.5],
        [2.5, 2.5]]])

In [61]:
arr1= np.random.randint(low = -10,high = 10, size = (2,3))
arr2= np.random.randint(low = -10,high = 10, size = (2,3))


In [62]:
arr1, arr2 #stacks arrow 

(array([[ -2,  -2, -10],
        [  1,   2,   4]], dtype=int32),
 array([[ 0,  4,  5],
        [ 1,  2, -7]], dtype=int32))

In [63]:
np.vstack((arr1,arr2)) #same column required in vertical stack-->mostly used stack

array([[ -2,  -2, -10],
       [  1,   2,   4],
       [  0,   4,   5],
       [  1,   2,  -7]], dtype=int32)

In [64]:
np.hstack((arr1,arr2)) #same column required in horizontal stack

array([[ -2,  -2, -10,   0,   4,   5],
       [  1,   2,   4,   1,   2,  -7]], dtype=int32)

In [65]:
np.concatenate((arr1,arr2),axis = 0) #stacks vertically

array([[ -2,  -2, -10],
       [  1,   2,   4],
       [  0,   4,   5],
       [  1,   2,  -7]], dtype=int32)

In [66]:
np.concatenate((arr1,arr2),axis = 1) #stacks horizontally

array([[ -2,  -2, -10,   0,   4,   5],
       [  1,   2,   4,   1,   2,  -7]], dtype=int32)

In [67]:
np.ceil(a) #provides ceiling value(rounds of to next integer) for float elements.-->2.3=3, 2.9 = 3, 2.01 = 3

array([[[3, 6, 2, 2, 6],
        [7, 5, 3, 7, 6],
        [0, 5, 5, 0, 5],
        [0, 1, 8, 1, 8],
        [5, 3, 8, 8, 1]],

       [[9, 8, 5, 9, 2],
        [5, 9, 6, 9, 4],
        [4, 2, 7, 7, 9],
        [5, 0, 3, 1, 4],
        [6, 8, 0, 6, 9]],

       [[7, 1, 3, 8, 3],
        [8, 3, 5, 9, 1],
        [8, 4, 3, 9, 4],
        [0, 6, 3, 3, 7],
        [3, 1, 4, 7, 0]]], dtype=int32)

In [68]:
np.sin(a) #provides sin value of each element of matrix

array([[[ 0.14112001, -0.2794155 ,  0.90929743,  0.90929743,
         -0.2794155 ],
        [ 0.6569866 , -0.95892427,  0.14112001,  0.6569866 ,
         -0.2794155 ],
        [ 0.        , -0.95892427, -0.95892427,  0.        ,
         -0.95892427],
        [ 0.        ,  0.84147098,  0.98935825,  0.84147098,
          0.98935825],
        [-0.95892427,  0.14112001,  0.98935825,  0.98935825,
          0.84147098]],

       [[ 0.41211849,  0.98935825, -0.95892427,  0.41211849,
          0.90929743],
        [-0.95892427,  0.41211849, -0.2794155 ,  0.41211849,
         -0.7568025 ],
        [-0.7568025 ,  0.90929743,  0.6569866 ,  0.6569866 ,
          0.41211849],
        [-0.95892427,  0.        ,  0.14112001,  0.84147098,
         -0.7568025 ],
        [-0.2794155 ,  0.98935825,  0.        , -0.2794155 ,
          0.41211849]],

       [[ 0.6569866 ,  0.84147098,  0.14112001,  0.98935825,
          0.14112001],
        [ 0.98935825,  0.14112001, -0.95892427,  0.41211849,
          0

In [69]:
np.round(a,decimals = 3) #rounds off each elements to 3 decimal places

array([[[3, 6, 2, 2, 6],
        [7, 5, 3, 7, 6],
        [0, 5, 5, 0, 5],
        [0, 1, 8, 1, 8],
        [5, 3, 8, 8, 1]],

       [[9, 8, 5, 9, 2],
        [5, 9, 6, 9, 4],
        [4, 2, 7, 7, 9],
        [5, 0, 3, 1, 4],
        [6, 8, 0, 6, 9]],

       [[7, 1, 3, 8, 3],
        [8, 3, 5, 9, 1],
        [8, 4, 3, 9, 4],
        [0, 6, 3, 3, 7],
        [3, 1, 4, 7, 0]]], dtype=int32)

In [70]:
np.fix(c)

array([[[ 0.,  0., -0., -0., -0.],
        [ 0.,  0., -0.,  0., -0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [-0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -0., -0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0., -0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., -0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0., -0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0., -0.,  0.,  0.],
        [ 0.,  0., -0.,  0.,  0.],
        [-0., -0.,  0., -0., -0.]]])

## Matrix Operation

Includes:  
            >Dot Product  
            >Inverse  

In [75]:
d=np.dot(a,c) #must match no of column of first matrix with no of row of second matrix

In [76]:
print(d)

[[[[  9.17326042   4.03627254  -3.32167059   1.70950769  -9.87844375]
   [  9.20556908   7.66248748  14.95573541  15.5729055    7.19591334]
   [  4.92788928   5.40456453   3.527102     5.39965616   5.50174741]]

  [[ 12.23079486   7.74533891  -0.63347245   3.54902812  -7.15143875]
   [ 16.78030671   9.11863895  22.38258577  23.30834091   5.71877503]
   [  8.74268407   9.40822207  -2.39720657  14.01237821  12.99642422]]

  [[  8.66767199   2.11680012  -1.01782001   4.69865699  -5.29370086]
   [  6.56986599   2.82306708  11.69964284  10.47530227   9.49327837]
   [  1.8683788    4.96982958   4.87086986   3.85500968   4.04740765]]

  [[ 10.70403028   2.81115862   4.57840288   1.58170171  -0.7680932 ]
   [  6.90223764   2.04419642  14.77750895  11.71165773   7.98432216]
   [ -3.79498164   1.72776535   4.62914688   6.02164642   2.53393265]]

  [[ 11.6343206    7.0509804    4.65802734  13.41438338   4.74256207]
   [ 18.42665155   0.09378084  19.74688268  18.34139093   8.00713017]
   [  9.4159

In [78]:
np.transpose(d) #changes row to column and vice versa

array([[[[  9.17326042,  15.05715672,   9.06654996],
         [ 12.23079486,  13.24537662,  11.59508756],
         [  8.66767199,  12.89990982,  11.42496665],
         [ 10.70403028,   9.04374196,   7.24718609],
         [ 11.6343206 ,  11.26567074,   5.06147445]],

        [[  9.20556908,  23.35792939,  15.14171856],
         [ 16.78030671,  22.04395619,  19.4160098 ],
         [  6.56986599,  15.46633351,  18.7590232 ],
         [  6.90223764,   6.24525104,   8.88095413],
         [ 18.42665155,  15.13396186,  12.18140052]],

        [[  4.92788928,  17.28116531,   7.19677858],
         [  8.74268407,  12.94060559,  12.10181833],
         [  1.8683788 ,   1.10060713,  10.53852907],
         [ -3.79498164,   2.48406128,   1.48525206],
         [  9.41598361,   7.88651304,   5.50975308]]],


       [[[  4.03627254,   9.53493286,   7.16961734],
         [  7.74533891,   8.45093895,   8.27609432],
         [  2.11680012,   7.07346348,   8.55833434],
         [  2.81115862,   3.46055097, 

In [81]:
np.trace(b) #sum of elements in main diagonal

array([3, 4])

In [89]:
#solving equations: x+2y = 1, 3x+5y = 2
arrx = np.array([[1,2],
             [3,5]])
arry = np.array([1,2])


In [91]:
#solves the linear equations and give value of x and y
np.linalg.solve(arrx,arry)

array([-1.,  1.])