In [40]:
import pandas as pd
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt

In [41]:
data_df = pd.read_csv("https://www.statlearning.com/s/Advertising.csv",index_col = 0)

In [42]:
data_df.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [43]:
X = data_df["TV"].to_numpy()
Y = data_df["sales"].to_numpy()

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [45]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 989)

In [46]:
X_train

array([191.1,  11.7,  50. ,  25.6,  88.3, 187.8,  17.2, 255.4,   0.7,
       125.7, 104.6, 222.4, 107.4, 172.5, 116. , 135.2, 188.4,  44.7,
       131.7, 213.4,   5.4, 175.1,  59.6, 250.9, 139.5,  76.4, 220.5,
       283.6,  68.4,  43.1, 214.7,  27.5, 280.7,  26.8, 187.9, 292.9,
       193.2, 182.6, 238.2, 230.1,  53.5, 134.3, 266.9,  62.3,  39.5,
       102.7,  48.3, 276.7, 164.5,  94.2, 290.7, 149.8, 222.4, 216.4,
       225.8, 261.3, 248.8,  57.5, 204.1, 253.8,  73.4,  96.2,  97.2,
       112.9, 296.4,  13.1, 206.9, 210.8, 151.5, 199.1,  13.2, 229.5,
       199.8,  90.4, 228. ,  31.5, 220.3, 177. ,  74.7, 195.4, 240.1,
        17.9, 109.8,   7.8,  23.8, 239.8, 170.2,  93.9, 243.2,   8.4,
       131.1,  69. , 209.6, 280.2,  16.9,  76.4,  75.5, 227.2, 184.9,
        70.6, 276.9, 171.3, 217.7, 215.4, 273.7,  19.6, 110.7,  56.2,
       228.3, 139.3, 184.9,  28.6, 142.9, 202.5, 240.1, 224. , 120.5,
       265.6, 193.7, 234.5,  25.1, 197.6, 123.1, 121. , 218.5, 289.7,
       293.6, 168.4,

In [47]:
Y_train

array([17.3,  7.3,  8.4,  9.5, 12.9, 15.6,  9.3, 19.8,  1.6, 15.9, 10.4,
       11.7, 11.5, 14.4, 11. , 17.2, 14.9, 10.1, 12.9, 17. ,  5.3, 14.9,
        9.7, 22.2, 10.3, 11.8, 20.1, 25.5, 13.6, 10.1, 17.4,  6.9, 16.1,
        8.8, 14.7, 21.4, 15.2, 21.2, 20.7, 22.1,  8.1, 11.2, 25.4,  9.7,
       10.8, 14. , 11.6, 11.8, 14.5,  9.7, 12.8, 10.1, 11.5, 22.6, 13.4,
       24.2, 18.9, 11.8, 19. , 17.6, 10.9, 11.4,  9.6, 11.9, 23.8,  5.3,
       12.9, 23.8, 18.5, 18.3,  5.6, 19.7, 11.4,  8.7, 21.5,  9.5, 24.7,
       17.1, 14.7, 22.4, 15.9,  8. , 16.7,  6.6,  9.2, 12.3, 11.7, 15.3,
       25.4,  5.7, 18. ,  9.3, 15.9, 14.8,  8.7,  9.4,  9.9, 14.8, 15.5,
       10.5, 27. , 19. , 19.4, 17.1, 20.8,  7.6, 16. ,  8.7, 15.5, 13.4,
       20.7,  7.3, 15. , 16.6, 13.2, 11.6, 14.2, 17.4, 19.2, 11.9,  8.5,
       16.6, 15.2, 11.6, 12.2, 25.4, 20.7, 11.7, 18.9, 12.9,  9.7, 11.9,
        4.8, 12.2, 11.7, 12.5,  8.6, 13.3, 14.1, 15.9, 10.6, 21.7, 20.2,
       21.8, 18. , 23.7,  6.7, 10.5,  8.8,  5.5,  5

In [48]:
lin_reg= LinearRegression()
lin_reg.fit(X_train.reshape(-1,1),Y_train)

LinearRegression()

In [49]:
print(f"y={lin_reg.intercept_} + {lin_reg.coef_[0]}x")

y=6.858509764823011 + 0.04842623831035565x


In [50]:
y_pred = lin_reg.predict(X_test.reshape(-1,1))
y_pred

array([18.09823968,  8.69870682,  7.27981804, 13.652711  ,  8.94083801,
       17.06191818,  8.70839207,  8.64543796,  7.79797879, 18.47596434,
       17.50259695, 14.93600631, 10.14180872, 14.87789483, 19.58976782,
       12.67934361, 20.7858959 , 13.53648803, 10.20960546, 10.09822511,
       20.48565323, 14.10791764, 14.77619973, 13.59944214, 10.49532026,
       11.49290077, 13.99169467, 15.42995395,  8.06916572, 11.72050409,
       10.50500551,  9.01347737,  7.76892305, 16.78588862, 13.45416342,
       11.08127775, 19.70114816, 12.17571073, 18.44690859, 20.62608932])

## Performance Metrics

In [51]:
from sklearn.metrics import max_error, mean_squared_error, mean_absolute_error, r2_score

In [52]:
max_error(y_test,y_pred)

np.float64(7.58976781661551)

In [53]:
mean_squared_error(y_test,y_pred)

10.209617603110354

In [54]:
mean_absolute_error(y_test,y_pred)

2.4910506561061587

In [55]:
r2_score(y_test,y_pred)

0.5697181446883102

In [56]:
#it means 56%

In [57]:
X = data_df["newspaper"].to_numpy()
Y = data_df["sales"].to_numpy()
