In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt

In [2]:
data_df = pd.read_csv("https://www.statlearning.com/s/Advertising.csv",index_col = 0)

In [3]:
data_df.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [4]:
X = data_df["radio"].to_numpy()
Y = data_df["sales"].to_numpy()

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 989)

In [7]:
X_train

array([28.7, 36.9, 11.6, 39. , 25.5, 21.1, 45.9, 26.9, 39.6, 36.9,  5.7,
        4.3, 14. , 18.1,  7.7, 41.7, 18.1, 25.8, 18.4, 24.6, 29.9, 22.5,
       12. , 36.5,  2.1, 26.7, 33.2, 42. , 44.5, 26.7, 24. ,  1.6, 13.9,
       33. , 17.2, 28.3, 18.4, 46.2, 34.3, 37.8,  2. ,  4.9, 43.8, 12.6,
       41.1, 29.6, 47. ,  2.3, 20.9,  4.9,  4.1,  1.3,  3.4, 41.7,  8.2,
       42.7, 27.1, 32.8, 32.9, 21.3, 17. , 14.8,  1.5, 17.4, 36.3,  0.4,
        8.4, 49.6, 41.3, 30.6, 15.9, 32.3,  3.1,  0.3, 37.7, 24.6, 49. ,
       33.4, 49.4, 47.7, 16.7, 37.6, 47.8, 38.9, 35.1,  4.1,  7.8, 43.5,
       49. , 27.2, 42.8,  9.3, 20.6, 10.1, 43.7,  0.8, 10.8, 15.8, 21. ,
       16. , 48.9, 39.7, 33.5, 23.6, 28.9, 20.1, 40.6,  5.7, 16.9, 14.5,
       43.9,  1.5, 29.3, 22.3,  7.3,  2.4, 28.5, 20. , 35.4,  3.4, 25.7,
       23.3, 34.6,  8.4,  5.4, 42.3, 27.7,  7.1, 27.5, 10.8,  7.6, 14.7,
        2.1,  5.2,  3.5,  5.1,  5.8, 35.8, 15.4, 13.9,  9.9, 43. , 30.2,
       38. , 27.7, 49.4, 12.1,  2.6,  0. , 28.1,  4

In [8]:
Y_train

array([17.3,  7.3,  8.4,  9.5, 12.9, 15.6,  9.3, 19.8,  1.6, 15.9, 10.4,
       11.7, 11.5, 14.4, 11. , 17.2, 14.9, 10.1, 12.9, 17. ,  5.3, 14.9,
        9.7, 22.2, 10.3, 11.8, 20.1, 25.5, 13.6, 10.1, 17.4,  6.9, 16.1,
        8.8, 14.7, 21.4, 15.2, 21.2, 20.7, 22.1,  8.1, 11.2, 25.4,  9.7,
       10.8, 14. , 11.6, 11.8, 14.5,  9.7, 12.8, 10.1, 11.5, 22.6, 13.4,
       24.2, 18.9, 11.8, 19. , 17.6, 10.9, 11.4,  9.6, 11.9, 23.8,  5.3,
       12.9, 23.8, 18.5, 18.3,  5.6, 19.7, 11.4,  8.7, 21.5,  9.5, 24.7,
       17.1, 14.7, 22.4, 15.9,  8. , 16.7,  6.6,  9.2, 12.3, 11.7, 15.3,
       25.4,  5.7, 18. ,  9.3, 15.9, 14.8,  8.7,  9.4,  9.9, 14.8, 15.5,
       10.5, 27. , 19. , 19.4, 17.1, 20.8,  7.6, 16. ,  8.7, 15.5, 13.4,
       20.7,  7.3, 15. , 16.6, 13.2, 11.6, 14.2, 17.4, 19.2, 11.9,  8.5,
       16.6, 15.2, 11.6, 12.2, 25.4, 20.7, 11.7, 18.9, 12.9,  9.7, 11.9,
        4.8, 12.2, 11.7, 12.5,  8.6, 13.3, 14.1, 15.9, 10.6, 21.7, 20.2,
       21.8, 18. , 23.7,  6.7, 10.5,  8.8,  5.5,  5

In [9]:
lin_reg= LinearRegression()
lin_reg.fit(X_train.reshape(-1,1),Y_train)

LinearRegression()

In [10]:
print(f"y={lin_reg.intercept_} + {lin_reg.coef_[0]}x")

y=9.303419276301533 + 0.20782813640425293x


In [11]:
y_pred = lin_reg.predict(X_test.reshape(-1,1))
y_pred

array([11.09074125, 17.67889317, 19.46621515,  9.69829274, 14.68616801,
       15.4343493 , 10.07238338, 17.32558534, 12.62866946, 17.92828694,
       16.26566185, 18.03220101, 16.90992907, 11.38170064, 10.03081775,
       13.37685075, 18.24002914, 18.94664481, 13.56389607, 11.73500847,
       17.53341348, 16.70210093, 16.9514947 , 12.27536163, 16.57740405,
        9.59437867, 14.27051174, 11.23622094, 11.58952878, 11.29856939,
       13.52233045, 17.47106504, 13.81328984, 18.67646823, 13.2937195 ,
       11.75579129,  9.90612087, 12.27536163, 12.52475539, 11.50639752])

## Performance Metrics

In [17]:
from sklearn.metrics import max_error, mean_squared_error, mean_absolute_error, r2_score

In [18]:
max_error(Y_test,y_pred)

np.float64(12.266215146469502)

In [19]:
mean_squared_error(Y_test,y_pred)

17.388522566863106

In [20]:
mean_absolute_error(Y_test,y_pred)

3.147586665973886

In [21]:
r2_score(Y_test,y_pred)

0.2671649378014248