In [16]:
import pandas as pd
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt

In [17]:
data_df = pd.read_csv("https://www.statlearning.com/s/Advertising.csv",index_col = 0)

In [18]:
data_df.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [19]:
X = data_df["newspaper"].to_numpy()
Y = data_df["sales"].to_numpy()

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 989)

In [22]:
X_train

array([ 18.2,  45.2,  18.4,   9.3,  73.4,   9.5,  69.3,   5.5,   8.7,
        79.2,  34.4,  49.8,  10.9,  30.7,  23.1,  45.9,  25.6,  20.6,
        34.6,  13.1,   9.4,  31.5,  43.1,  72.3,  26.6,  22.3,  37.9,
        66.2,  35.6,  35.1,   4. ,  20.7,  37. ,  19.3,  17.9,  43.2,
        65.7,  58.7,   5.3,  69.2,  21.4,   9.3,   5. ,  18.3,   5.8,
         8.4,   8.5,  23.7,  47.4,   8.1,   8.5,  24.3,  13.1,  39.6,
        56.5,  54.7,  22.9,  23.5,  46. ,  30. ,  12.9,  38.9,  30. ,
        38.6, 100.9,  25.6,  26.4,  37.7,  58.5,  38.7,  49.6,  74.2,
        34.6,  23.2,  32. ,   2.2,   3.2,  38.7,  45.7,  52.9,  22.9,
        21.6,  51.4,  50.6,  65.9,  36.9,  35.2,  50.5,  44.3,   2.1,
        28.9,   0.9,  10.7,  21.4,  89.4,  14.8,   6. ,  49.9,  22. ,
        40.8,  41.8,  37.7,  59. ,  57.6,  59.7,  17. ,  63.2,  29.7,
        26.2,  10.2,   1.7,  33. ,  12.6,  31.6,   8.7,  15.6,  14.2,
         0.3,  75.6,  84.8,  43.3,  14.2,  12.4,  48.7,  27.4,  51.2,
         1.8,  12.8,

In [23]:
Y_train

array([17.3,  7.3,  8.4,  9.5, 12.9, 15.6,  9.3, 19.8,  1.6, 15.9, 10.4,
       11.7, 11.5, 14.4, 11. , 17.2, 14.9, 10.1, 12.9, 17. ,  5.3, 14.9,
        9.7, 22.2, 10.3, 11.8, 20.1, 25.5, 13.6, 10.1, 17.4,  6.9, 16.1,
        8.8, 14.7, 21.4, 15.2, 21.2, 20.7, 22.1,  8.1, 11.2, 25.4,  9.7,
       10.8, 14. , 11.6, 11.8, 14.5,  9.7, 12.8, 10.1, 11.5, 22.6, 13.4,
       24.2, 18.9, 11.8, 19. , 17.6, 10.9, 11.4,  9.6, 11.9, 23.8,  5.3,
       12.9, 23.8, 18.5, 18.3,  5.6, 19.7, 11.4,  8.7, 21.5,  9.5, 24.7,
       17.1, 14.7, 22.4, 15.9,  8. , 16.7,  6.6,  9.2, 12.3, 11.7, 15.3,
       25.4,  5.7, 18. ,  9.3, 15.9, 14.8,  8.7,  9.4,  9.9, 14.8, 15.5,
       10.5, 27. , 19. , 19.4, 17.1, 20.8,  7.6, 16. ,  8.7, 15.5, 13.4,
       20.7,  7.3, 15. , 16.6, 13.2, 11.6, 14.2, 17.4, 19.2, 11.9,  8.5,
       16.6, 15.2, 11.6, 12.2, 25.4, 20.7, 11.7, 18.9, 12.9,  9.7, 11.9,
        4.8, 12.2, 11.7, 12.5,  8.6, 13.3, 14.1, 15.9, 10.6, 21.7, 20.2,
       21.8, 18. , 23.7,  6.7, 10.5,  8.8,  5.5,  5

In [24]:
lin_reg= LinearRegression()
lin_reg.fit(X_train.reshape(-1,1),Y_train)

LinearRegression()

In [25]:
print(f"y={lin_reg.intercept_} + {lin_reg.coef_[0]}x")

y=12.005089411415938 + 0.06864893649775611x


In [26]:
y_pred = lin_reg.predict(X_test.reshape(-1,1))
y_pred

array([12.60233516, 12.82201176, 17.15375965, 12.62292984, 13.41239261,
       12.64352452, 12.95244474, 16.50845965, 13.5359607 , 13.27509474,
       15.10115645, 12.25222558, 19.83106817, 13.21331069, 13.34374367,
       12.80141707, 16.93408305, 16.05537666, 13.26136495, 14.53137027,
       15.83570007, 12.41698303, 12.51309154, 13.76250219, 15.62288836,
       12.51309154, 13.3162841 , 12.44444261, 14.04396283, 12.25222558,
       14.23617985, 15.10115645, 15.46499581, 13.35060857, 13.14466176,
       13.78309687, 14.95699368, 14.1812607 , 13.87920538, 12.44444261])

## Performance Metrics

In [27]:
from sklearn.metrics import max_error, mean_squared_error, mean_absolute_error, r2_score

In [28]:
max_error(Y_test,y_pred)

np.float64(9.953759648747646)

In [29]:
mean_squared_error(Y_test,y_pred)

25.818190189008135

In [30]:
mean_absolute_error(Y_test,y_pred)

4.169913441417341

In [31]:
r2_score(Y_test,y_pred)

-0.08810135767789262